// Reproduce the ORIGINAL gotcha-31 bug on demand: generate the module with
// ENDS_TEXT empty, which is exactly what Root.jsx used to receive.
//
//   node scripts/_break_ends.mjs          -> break it
//   node scripts/_break_ends.mjs --fix    -> put it back (via a real render)
//
// This exists to keep scan_visibility.py honest. A verification tool that
// reports a KNOWN-BROKEN file as clean is worse than no tool, and the only way
// to know a detector works is to watch it catch the bug it was written for. So
// the broken state is reproducible in one command, and the detector is run
// against it as a negative control.
//
// It writes a throwaway file, so it refuses to run unless src/lyrics.generated.js
// is the generated file (it is gitignored and always rewritten by a render).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// fileURLToPath, NOT import.meta.url.pathname: this repo lives under
// "Default Project", and a space in the path comes back as %20 from a manual
// .pathname strip, so the file is then not found. A hand-rolled unescape is
// exactly the sort of shortcut that costs twenty minutes.
const HERE = path.dirname(fileURLToPath(import.meta.url));
const GEN = path.join(HERE, "..", "src", "lyrics.generated.js");

if (process.argv.includes("--fix")) {
  console.log("  run a render (or --prepare-only) to regenerate the module properly");
  process.exit(0);
}

const src = process.argv[2] || "G:\\Lyrical Video\\Allare\\Allare Remotion.lrc";
const body = fs.readFileSync(GEN, "utf8");
const lrc = fs.readFileSync(src, "utf8");

// Same escaping writeGenerated uses.
const esc = (s) => s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const out =
  "// GENERATED by scripts/_break_ends.mjs -- DELIBERATELY BROKEN. Do not ship.\n\n" +
  "export const LRC_TEXT = `" + esc(lrc) + "`;\n\n" +
  "// ENDS_TEXT is EMPTY ON PURPOSE. This is the state Root.jsx was in before\n" +
  "// gotcha 31: every cue fell back to an estimated end (the next line's start).\n" +
  "export const ENDS_TEXT = \"\";\n\n" +
  "export const AUDIO_FILE = \"\";\n\n" +
  "export const LEGACY_FONT_FILE = \"\";\n\n" +
  "export const LEGACY_FONT_FAMILY = \"\";\n\n" +
  "export const FONT_FILE = \"\";\n\n" +
  "export const FONT_FAMILY_NAME = \"\";\n\n" +
  "export const AUDIO_SECONDS = 0;\n";

fs.writeFileSync(GEN, out, "utf-8");
console.log("  BROKE src/lyrics.generated.js (ENDS_TEXT is now empty).");
console.log("  Render a short clip, then run scan_visibility.py on it as the");
console.log("  negative control. A detector that does not FAIL here is not working.");
